#!/usr/bin/env python3
"""
Radiant Quest Marker - build script.

  python build/package.py            # generate everything
  python build/package.py --no-zip   # skip the archive

Generates:
  Database/quests.tsv                 input for GenerateQuestMarkers.pas
  Documentation/QUEST_DATABASE.md     human readable database
  fomod/ModuleConfig.xml              installer definition
  dist/RadiantQuestMarker-<ver>.7z    (zip fallback if 7z is unavailable)

The JSON in Database/ is the single source of truth. Never hand-edit the
generated files - edit quests.json and re-run this.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path
from xml.sax.saxutils import escape

VERSION = "1.1.1"
_DIR = Path(__file__).resolve().parent
ROOT = _DIR if (_DIR / "Database").exists() else _DIR.parent

# module -> (plugin name, required master esm, fomod flag, display name)
MODULES = {
    "Main":       ("QuestMarkers_Main.esp",       "Fallout4.esm",       "mod_main",       "Main story & faction paths"),
    "Side":       ("QuestMarkers_Side.esp",       "Fallout4.esm",       "mod_side",       "Side quests"),
    "Radiant":    ("QuestMarkers_Radiant.esp",    "Fallout4.esm",       "mod_radiant",    "Radiant & repeatable"),
    "Defend":     ("QuestMarkers_Defend.esp",     "Fallout4.esm",       "mod_defend",     "Settlement defense"),
    "Vanilla":    ("QuestMarkers_Vanilla.esp",    "Fallout4.esm",       "mod_vanilla",    "Base game"),
    "Settlement": ("QuestMarkers_Settlement.esp", "Fallout4.esm",       "mod_settlement", "Settlement quests"),
    "Timed":      ("QuestMarkers_Timed.esp",      "Fallout4.esm",       "mod_timed",      "Timed radiant quests"),
    "Automatron": ("QuestMarkers_Automatron.esp", "DLCRobot.esm",       "mod_automatron", "Automatron"),
    "FarHarbor":  ("QuestMarkers_FarHarbor.esp",  "DLCCoast.esm",       "mod_farharbor",  "Far Harbor"),
    "NukaWorld":  ("QuestMarkers_NukaWorld.esp",  "DLCNukaWorld.esm",   "mod_nukaworld",  "Nuka-World"),
    "VaultTec":   ("QuestMarkers_VaultTec.esp",   "DLCworkshop03.esm",  "mod_vaulttec",   "Vault-Tec Workshop"),
    "OtherDLC":   ("QuestMarkers_OtherDLC.esp",   "DLCworkshop02.esm",  "mod_otherdlc",   "Contraptions / Wasteland Workshop"),
    "NextGen":    ("QuestMarkers_NextGen.esp",    None,                 "mod_nextgen",    "Next-Gen / Creation Club"),
}

STYLES = {"desc": "Descriptive", "sym": "Compact"}

FACTION_ORDER = ["Minutemen", "Brotherhood of Steel", "Railroad", "Institute",
                 "Far Harbor", "Nuka-World", "Other"]
SOURCE_ORDER = [(None, "Vanilla"), ("Automatron", "Automatron"),
                ("Far Harbor", "Far Harbor"), ("Nuka-World", "Nuka-World"),
                ("Vault-Tec Workshop", "Vault-Tec Workshop"),
                ("Creation Club", "Next-Gen / Creation Club")]


def load_db():
    with open(ROOT / "Database" / "quests.json", encoding="utf-8") as fh:
        return json.load(fh)


def load_aliases():
    with open(ROOT / "Database" / "aliases.json", encoding="utf-8") as fh:
        return json.load(fh)


# ------------------------------------------------------------------ TSV

def write_tsv(db):
    out = [
        "# Generated by build/package.py - do not hand edit.",
        "# Source of truth: Database/quests.json",
        "# formID|editorID|originalName|tag|category|faction|dlc|repeatable|"
        "timed|settlementRelated|sourcePlugin|module|confidence|evidence",
    ]
    for q in db["quests"]:
        out.append("|".join([
            q["formID"] or "",
            q["editorID"] or "",
            q["originalName"],
            q["tag"] or "",
            q["category"],
            q["faction"],
            q["dlc"] or "",
            "true" if q["repeatable"] else "false",
            "true" if q["timed"] else "false",
            "true" if q["settlementRelated"] else "false",
            q["sourcePlugin"],
            q["module"] or "",
            q["confidence"],
            (q.get("evidence") or "").replace("|", "/"),
        ]))
    path = ROOT / "Database" / "quests.tsv"
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"  wrote {path.relative_to(ROOT)} ({len(db['quests'])} rows)")


# ------------------------------------------------- QUEST_DATABASE.md

def write_quest_database(db, aliases):
    desc = aliases["styles"]["descriptive"]
    comp = aliases["styles"]["compact"]
    counts = {}
    for q in db["quests"]:
        counts[q["confidence"]] = counts.get(q["confidence"], 0) + 1

    L = [
        "# Quest Database",
        "",
        f"Generated from `Database/quests.json` by `build/package.py`. Target runtime: {db['targetRuntime']}.",
        "",
        "## Confidence states",
        "",
        "| State | Meaning | Tagged by default |",
        "| --- | --- | --- |",
        "| `verified` | Confirmed against local game records by `AuditQuests.pas`. | yes |",
        "| `likely` | Strong public evidence, not yet confirmed against records. | yes |",
        "| `unverified` | Listed for completeness only. | no |",
        "| `excluded` | Reviewed and deliberately left untagged. | never |",
        "",
        "### Current counts",
        "",
        "| State | Entries |",
        "| --- | --- |",
    ]
    for state in ("verified", "likely", "unverified", "excluded"):
        L.append(f"| {state} | {counts.get(state, 0)} |")

    L += [
        "",
        "> **Nothing in this file ships as `verified` out of the box.** Verification requires",
        "> reading the QUST records in your own install. Run `AuditQuests.pas` first; it",
        "> resolves the empty FormID and EditorID columns below and promotes entries whose",
        "> records actually carry radiant signals.",
        "",
    ]

    for dlc_key, heading in SOURCE_ORDER:
        rows = [q for q in db["quests"] if q["dlc"] == dlc_key]
        if not rows:
            continue
        L += ["", f"# {heading}", ""]
        factions = [f for f in FACTION_ORDER if any(r["faction"] == f for r in rows)]
        for fac in factions:
            frows = [r for r in rows if r["faction"] == fac]
            if len(factions) > 1:
                L += [f"## {fac}", ""]
            L += [
                "| Quest | FormID | EditorID | Category | Repeatable | Tag | Confidence |",
                "| --- | --- | --- | --- | --- | --- | --- |",
            ]
            for r in sorted(frows, key=lambda x: (x["confidence"] != "verified",
                                                  x["confidence"], x["originalName"])):
                tag_d = desc.get(r["tag"], "-") if r["tag"] else "-"
                tag_c = comp.get(r["tag"], "-") if r["tag"] else "-"
                tag_cell = "-" if tag_d == "-" else f"`{tag_d}` / `{tag_c}`"
                L.append(
                    f"| {r['originalName']} "
                    f"| {r['formID'] or '_pending audit_'} "
                    f"| {r['editorID'] or '_pending audit_'} "
                    f"| {r['category']} "
                    f"| {'yes' if r['repeatable'] else 'no'} "
                    f"| {tag_cell} "
                    f"| {r['confidence']} |"
                )
            L.append("")

    L += [
        "# Deliberately excluded",
        "",
        "Listed so the exclusions are auditable rather than invisible.",
        "",
        "| Quest | Source | Why excluded |",
        "| --- | --- | --- |",
    ]
    for r in db["quests"]:
        if r["confidence"] == "excluded":
            L.append(f"| {r['originalName']} | {r['sourcePlugin']} | {r['evidence']} |")

    L += [
        "",
        "# Rule-discovered quests",
        "",
        "The Minutemen settlement families are not enumerated by name here. Their display",
        "names contain text-replacement tokens such as `<Alias=Workshop>`, so the name a",
        "player sees is generated per settlement and is not a stable match key. They are",
        "discovered by EditorID family instead - see `Database/radiant_rules.json`,",
        "`radiantEditorIDPatterns`. `AuditQuests.pas` writes them into",
        "`output/quests.candidate.tsv` with real FormIDs from your install.",
        "",
        "# Known-empty categories",
        "",
        "| DLC | Radiant quests | Note |",
        "| --- | --- | --- |",
        "| Vault-Tec Workshop | 0 expected | The vault experiments are workshop mechanics, not repeatable QUST records. |",
        "| Contraptions Workshop | 0 expected | No quest content. |",
        "| Wasteland Workshop | 0 expected | No quest content. |",
        "",
    ]
    path = ROOT / "Documentation" / "QUEST_DATABASE.md"
    path.write_text("\n".join(L), encoding="utf-8")
    print(f"  wrote {path.relative_to(ROOT)}")


# ------------------------------------------------------------- FOMOD

def _files_block(module, style_key, indent):
    plugin = MODULES[module][0]
    folder = f"{STYLES[style_key]}/{module}"
    pad = " " * indent
    return (f'{pad}<files>\n'
            f'{pad}  <folder source="{folder}" destination="" priority="0" />\n'
            f'{pad}</files>\n')


def write_module_config():
    x = []
    a = x.append
    a('<?xml version="1.0" encoding="utf-8"?>')
    a('<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"')
    a('        xsi:noNamespaceSchemaLocation="http://qconsulting.ca/fo3/ModConfig5.0.xsd">')
    a('  <moduleName>Radiant Quest Marker</moduleName>')
    a('  <moduleImage path="fomod/images/header.png" showImage="true" showFade="true" height="-1" />')
    a('  <requiredInstallFiles>')
    a('    <folder source="Documentation" destination="Docs/RadiantQuestMarker" priority="0" />')
    a('  </requiredInstallFiles>')
    a('  <installSteps order="Explicit">')

    # ---- step 1: content
    a('    <installStep name="Quest Content">')
    a('      <optionalFileGroups order="Explicit">')
    a('        <group name="Which quests should be tagged?" type="SelectExactlyOne">')
    a('          <plugins order="Explicit">')

    all_flags = "".join(
        f'                <flag name="{MODULES[m][2]}">On</flag>\n' for m in MODULES
    )
    a('            <plugin name="Vanilla + DLC (recommended)">')
    a('              <description>Tags base game and every official DLC module whose master is present. '
      'Modules whose masters are missing are skipped automatically.</description>')
    a('              <conditionFlags>')
    a(all_flags.rstrip("\n"))
    a('              </conditionFlags>')
    a('              <typeDescriptor><type name="Recommended" /></typeDescriptor>')
    a('            </plugin>')

    a('            <plugin name="Vanilla only">')
    a('              <description>Base game quests only. No DLC or Creation Club records are installed.</description>')
    a('              <conditionFlags>')
    a('                <flag name="mod_vanilla">On</flag>')
    a('                <flag name="mod_settlement">On</flag>')
    a('                <flag name="mod_timed">On</flag>')
    a('              </conditionFlags>')
    a('              <typeDescriptor><type name="Optional" /></typeDescriptor>')
    a('            </plugin>')

    a('            <plugin name="Pick DLC manually">')
    a('              <description>Choose individual DLC modules on the next page.</description>')
    a('              <conditionFlags>')
    a('                <flag name="mod_vanilla">On</flag>')
    a('                <flag name="mod_settlement">On</flag>')
    a('                <flag name="mod_timed">On</flag>')
    a('                <flag name="pick_dlc">On</flag>')
    a('              </conditionFlags>')
    a('              <typeDescriptor><type name="Optional" /></typeDescriptor>')
    a('            </plugin>')
    a('          </plugins>')
    a('        </group>')
    a('      </optionalFileGroups>')
    a('    </installStep>')

    # ---- step 2: pick DLC (visible only when pick_dlc)
    a('    <installStep name="DLC Modules">')
    a('      <visible>')
    a('        <flagDependency flag="pick_dlc" value="On" />')
    a('      </visible>')
    a('      <optionalFileGroups order="Explicit">')
    a('        <group name="Official DLC" type="SelectAny">')
    a('          <plugins order="Explicit">')
    for m in ("Automatron", "FarHarbor", "NukaWorld", "VaultTec", "OtherDLC"):
        plugin, master, flag, label = MODULES[m]
        a(f'            <plugin name="{escape(label)}">')
        a(f'              <description>Tag repeatable {escape(label)} quests. '
          f'Greyed out if {master} is not installed.</description>')
        a('              <conditionFlags>')
        a(f'                <flag name="{flag}">On</flag>')
        a('              </conditionFlags>')
        a('              <typeDescriptor>')
        a('                <dependencyType>')
        a('                  <defaultType name="Optional" />')
        a('                  <patterns>')
        a('                    <pattern>')
        a('                      <dependencies operator="And">')
        a(f'                        <fileDependency file="{master}" state="Missing" />')
        a('                      </dependencies>')
        a('                      <type name="NotUsable" />')
        a('                    </pattern>')
        a('                  </patterns>')
        a('                </dependencyType>')
        a('              </typeDescriptor>')
        a('            </plugin>')
    a('          </plugins>')
    a('        </group>')
    a('      </optionalFileGroups>')
    a('    </installStep>')

    # ---- step 3: tag style
    a('    <installStep name="Quest Tag Style">')
    a('      <optionalFileGroups order="Explicit">')
    a('        <group name="How should tags look?" type="SelectExactlyOne">')
    a('          <plugins order="Explicit">')
    a('            <plugin name="Descriptive (recommended)">')
    a('              <description>[Brotherhood - Radiant] Cleansing the Commonwealth&#10;'
      '[Far Harbor - Radiant] Blood Tide&#10;[Minutemen - Settlement Defense] Defend Abernathy Farm'
      '&#10;&#10;Readable at a glance. Longer entries in the Pip-Boy list.</description>')
    a('              <conditionFlags><flag name="style">desc</flag></conditionFlags>')
    a('              <typeDescriptor><type name="Recommended" /></typeDescriptor>')
    a('            </plugin>')
    a('            <plugin name="Compact symbols">')
    a('              <description>[R-BOS] Cleansing the Commonwealth&#10;[R-FH] Blood Tide&#10;'
      '[MM-DEF] Defend Abernathy Farm&#10;&#10;Short prefixes, plain ASCII. No font replacer or '
      'UI framework needed. Legend is in the README.</description>')
    a('              <conditionFlags><flag name="style">sym</flag></conditionFlags>')
    a('              <typeDescriptor><type name="Optional" /></typeDescriptor>')
    a('            </plugin>')
    a('          </plugins>')
    a('        </group>')
    a('      </optionalFileGroups>')
    a('    </installStep>')

    # ---- step 4: special categories
    a('    <installStep name="Special Categories">')
    a('      <optionalFileGroups order="Explicit">')
    a('        <group name="Extra categories" type="SelectAny">')
    a('          <plugins order="Explicit">')
    a('            <plugin name="Timed radiant quests">')
    a('              <description>Separately tag radiant quests that fail after a time limit, so you '
      'can tell an expiring quest from an open-ended one.</description>')
    a('              <conditionFlags><flag name="opt_timed">On</flag></conditionFlags>')
    a('              <typeDescriptor><type name="Recommended" /></typeDescriptor>')
    a('            </plugin>')
    a('            <plugin name="Settlement quests">')
    a('              <description>Tag settlement establishment and settlement defence quests. Only '
      'quests whose records show genuine radiant behaviour are included.</description>')
    a('              <conditionFlags><flag name="opt_settlement">On</flag></conditionFlags>')
    a('              <typeDescriptor><type name="Recommended" /></typeDescriptor>')
    a('            </plugin>')
    a('            <plugin name="Next-Gen / Creation Club labels">')
    a('              <description>Label quests that arrived with the Next-Gen update as [Next-Gen]. '
      'This is a source label, completely independent of the radiant classification.</description>')
    a('              <conditionFlags><flag name="opt_nextgen">On</flag></conditionFlags>')
    a('              <typeDescriptor><type name="Optional" /></typeDescriptor>')
    a('            </plugin>')
    a('          </plugins>')
    a('        </group>')
    a('      </optionalFileGroups>')
    a('    </installStep>')
    a('  </installSteps>')

    # ---- conditional installs: style x module, gated on master presence
    a('  <conditionalFileInstalls>')
    a('    <patterns>')
    extra_flag = {"Timed": "opt_timed", "Settlement": "opt_settlement", "NextGen": "opt_nextgen"}
    for style_key in STYLES:
        for module, (plugin, master, flag, label) in MODULES.items():
            a('      <pattern>')
            a('        <dependencies operator="And">')
            a(f'          <flagDependency flag="style" value="{style_key}" />')
            a(f'          <flagDependency flag="{flag}" value="On" />')
            if module in extra_flag:
                a(f'          <flagDependency flag="{extra_flag[module]}" value="On" />')
            if master:
                a(f'          <fileDependency file="{master}" state="Active" />')
            a('        </dependencies>')
            a(_files_block(module, style_key, 8).rstrip("\n"))
            a('      </pattern>')
    a('    </patterns>')
    a('  </conditionalFileInstalls>')
    a('</config>')

    path = ROOT / "fomod" / "ModuleConfig.xml"
    path.write_text("\n".join(x) + "\n", encoding="utf-8")
    n = len(STYLES) * len(MODULES)
    print(f"  wrote {path.relative_to(ROOT)} ({n} conditional install patterns)")


def write_info_xml():
    xml = f"""<?xml version="1.0" encoding="utf-8"?>
<fomod>
  <Name>Radiant Quest Marker</Name>
  <Author>Radiant Quest Marker project</Author>
  <Version MachineVersion="{VERSION}">{VERSION}</Version>
  <Description>
    Tags radiant, repeatable, timed and settlement quests in the Pip-Boy log so they
    are distinguishable from one-time story and side content. Display names only.
    No quest is removed, disabled or altered in behaviour.
  </Description>
  <Website></Website>
  <Groups>
    <element>Gameplay Effects and Changes</element>
    <element>User Interface</element>
  </Groups>
</fomod>
"""
    path = ROOT / "fomod" / "info.xml"
    path.write_text(xml, encoding="utf-8")
    print(f"  wrote {path.relative_to(ROOT)}")


# ------------------------------------------------------------ packaging

def make_plugin_tree():
    """Create the folder layout the FOMOD expects, so a build is installable
    the moment the .esp files are dropped in."""
    made = 0
    for style in STYLES.values():
        for module in MODULES:
            d = ROOT / "Plugins" / style / module
            d.mkdir(parents=True, exist_ok=True)
            keep = d / ".gitkeep"
            if not keep.exists():
                keep.write_text(
                    f"Drop {MODULES[module][0]} here after running "
                    f"GenerateQuestMarkers.pas with TAG_STYLE = "
                    f"'{'descriptive' if style == 'Descriptive' else 'compact'}'.\n",
                    encoding="utf-8")
                made += 1
    print(f"  prepared Plugins/ tree ({made} placeholders)")


def package(db):
    dist = ROOT / "dist"
    dist.mkdir(exist_ok=True)
    staging = dist / "staging"
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir()

    for d in ("fomod", "Documentation", "Database", "Scripts"):
        shutil.copytree(ROOT / d, staging / d)
    if (ROOT / "Plugins").exists():
        for style in STYLES.values():
            src = ROOT / "Plugins" / style
            if src.exists():
                shutil.copytree(src, staging / style)

    missing = [p for p in staging.rglob("*") if False]  # placeholder for future checks
    archive = dist / f"RadiantQuestMarker-{VERSION}"
    with zipfile.ZipFile(f"{archive}.zip", "w", zipfile.ZIP_DEFLATED) as z:
        for p in staging.rglob("*"):
            if p.is_file():
                z.write(p, p.relative_to(staging))
    shutil.rmtree(staging)
    print(f"  wrote {(Path('dist') / (archive.name + '.zip'))}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-zip", action="store_true")
    args = ap.parse_args()

    print("Radiant Quest Marker build")
    db = load_db()
    aliases = load_aliases()

    esp_count = sum(1 for q in db["quests"] if q["confidence"] in ("verified", "likely") and q["tag"])
    print(f"  database: {len(db['quests'])} entries, {esp_count} taggable by default")

    # write_tsv(db)
    write_quest_database(db, aliases)
    # write_module_config()  # preserved custom 2-step FOMOD installer
    write_info_xml()
    make_plugin_tree()
    if not args.no_zip:
        package(db)
    print("Done.")


if __name__ == "__main__":
    main()
